### PR TITLE
Vendor `githubrelease`

### LINKED ISSUE #44: Poetry install is failing out of the box
```shellsession
$ poetry install
Configuration file exists at /Users/offbyone/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/offbyone/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Updating dependencies
Resolving dependencies... (4.4s)

Package docutils (0.21.post1) not found.
```

This is remediated by bumping the lower bound python version, since the issue -- which Poetry does _not_ report -- is that Docutils 0.21 needs 3.9+ to work.

### PR DESCRIPTION
**Pull request by offbyone**
PR #43 would do this, but that doesn't work with PyPi; we can't refer to
direct URL dependencies.

This pulls in the githubrelease code.

Also, as a drive-by, fix #44 by setting a higher floor for supported Python versions

### CODE REVIEW

**Comment by justinmayer** [comment]
Merged manually (since the author of the commits herein were somehow associated with the `botpub` account).

Many thanks, Chris! Hopefully this will obviate the need for the silly hacks we've been using up until this point. 🥇

**Comment by justinmayer** [comment]
Hey Chris. I just tested these changes in the AutoPub 0.4.0 release by trying to publish a new version of the Render Math plugin, and unfortunately there seems to be a problem: https://github.com/pelican-plugins/render-math/actions/runs/11642308440/job/32421766961#step:6:28

```python
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/autopub/create_github_release.py", line 21, in create_github_release
    from .vendor.github_release import gh_asset_upload, gh_release_create
ImportError: attempted relative import with no known parent package
Error: Process completed with exit code 1.
```

**Comment by offbyone** [comment]
I thought I'd tested that path. Damn it...

**Comment by offbyone** [comment]
I've identified the fix, I believe #46 resolves it; I've confirmed that locally the code gets past the point where you're seeing that issue.

Sorry about the back and forth.

**Pull request closed without merging**
