### PR TITLE
Append "Contributed by" to the github contributor

### PR DESCRIPTION
**Pull request by marcoacierno**

### CODE REVIEW

**Review by patrick91 — APPROVED** [review]
Nice!

**Comment by patrick91** [comment]
@justinmayer took the freedom of merging this, hope that's ok :)

**Comment by justinmayer** [comment]
@patrick91: I wouldn't mind having had a look first, but no worries at all. In this case, I would have added "via" in between the contributor name and PR number, which I just did in 3115771. 😊

**Comment by patrick91** [comment]
> @patrick91: I wouldn't mind having had a look first, but no worries at all. In this case, I would have added "via" in between the contributor name and PR number, which I just did in [3115771](https://github.com/autopub/autopub/commit/31157712959b0ef6f569aee5fe75948e8a3b93ba). 😊

Oh, that's better! Thanks for checking 😊

**Pull request merged**
